package service;

import model.entity.PowerPlant;

/**
 * Interface definition for Power Plant operations.
 */
public interface PowerPlantService {

    /**
     * Calculates the actual energy production for the hour.
     * Takes into account dynamic factors (solar, wind).
     * Returns 0 if the plant is under construction or inactive.
     */
    double calculateProduction(PowerPlant plant, int hour);

    /**
     * Calculates the pollution generated by the plant today.
     */
    double calculatePollution(PowerPlant plant);

    /**
     * Updates construction or upgrade progress.
     * Decrements remaining time and updates status when complete.
     */
    void updateProgress(PowerPlant plant);

    /**
     * Calculates and sets the cost and time required for the next upgrade.
     * Stores results in plant.upgradeCost and plant.upgradeTime.
     */
    void prepareNextLevelStats(PowerPlant plant);

    /**
     * Updates the plant's stats (production, cost, etc.) for the next level.
     */
    void upgradeLevel(PowerPlant plant);

    /**
     * Stores surplus energy in the plant's battery.
     * Returns the amount actually stored.
     */
    double storeEnergy(PowerPlant plant, double amount);

    /**
     * Consumes energy from the plant's battery to meet demand.
     * Returns the amount actually consumed.
     */
    double consumeStoredEnergy(PowerPlant plant, double demand);

    /**
     * Toggles the plant status between ACTIVE and PAUSED.
     * Does nothing if plant is UNDER_CONSTRUCTION or BROKEN.
     */
    void togglePlantStatus(PowerPlant plant);
}
