package service;

import model.entity.Residence;

/**
 * Interface definition for Residence operations.
 */
public interface ResidenceService {

    /**
     * Regenerates random values for energy demand and purchasing power
     * based on the residence's current level.
     */
    void regenerateDailyValues(Residence residence);

    /**
     * Calculates the total energy demand for the residence building.
     */
    double calculateTotalDemand(Residence residence);

    /**
     * Updates the occupancy (number of residents) based on city happiness.
     */
    void updateOccupancy(Residence residence, double happiness);

    /**
     * Calculates the daily revenue generated by this residence.
     */
    double calculateRevenue(Residence residence, double electricityPrice);

    /**
     * Upgrades the residence to the next level, increasing its capacity and stats.
     */
    void upgradeLevel(Residence residence);
}
